backend:
  name: git-gateway
  branch: v2 # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - {label: "Day", name: "day", widget: "string"}
          - {label: "Times", name: "times", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Playlists"
        name: "playlists"
        file: "content/pages/playlists.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "playlist" # Used in routes, e.g., /admin/collections/playlist
    label: "Playlist" # Used in the UI
    folder: "content/playlists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}